#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# global settings
yabai -m config mouse_follows_focus             on
yabai -m config focus_follows_mouse             autofocus
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   float
yabai -m config window_border                   off
yabai -m config window_border_width             4
yabai -m config active_window_border_color      0xB2EBDBB2
yabai -m config normal_window_border_color      0xB2282828
yabai -m config window_opacity                  on
yabai -m config active_window_opacity 			1.0
yabai -m config normal_window_opacity 			0.9
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                  0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      0

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Masters"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Fun"
yabai -m space 5 --label "Whatever"

# Space config
yabai -m config --space 5 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off
yabai -m rule --add app="Tor Browser"  manage=off border=off

# Primary
yabai -m rule --add app="Preview"               space=Primary
yabai -m rule --add app="Zoom"                  space=Primary
yabai -m rule --add app="Finder"                space=Primary
yabai -m rule --add app="Safari"                space=Primary

# Masters
yabai -m rule --add app="GoodNotes"             space=Masters
yabai -m rule --add app="Microsoft OneNote"     space=Masters


# Tools
yabai -m rule --add app="Terminal"              space=Tools
yabai -m rule --add app="VimR"                  space=Tools
yabai -m rule --add app="Sublime Text"          space=Tools
yabai -m rule --add app="PyCharm"          		space=Tools

# Fun
yabai -m rule --add app="IINA"                  space=Fun
yabai -m rule --add app="Spotify"               space=Fun
yabai -m rule --add app="WhatsApp"              space=Fun
yabai -m rule --add app="Telegram"              space=Fun

# Whatever
yabai -m rule --add app="^System Preferences$"  space=Whatever
yabai -m rule --add app="Tor Browser"  space=Whatever

# Rules
yabai -m signal --add event=window_title_changed app="Safari" title="RWTHmoodle" action="yabai -m window --space  Masters && yabai -m space --focus Masters"
yabai -m signal --add event=window_title_changed app="Safari" title="GitHub" action="yabai -m window --space  Tools && yabai -m space --focus Tools"
yabai -m signal --add event=window_title_changed app="Safari" title="YouTube" action="yabai -m window --space  Fun && yabai -m space --focus Fun"
yabai -m signal --add event=window_title_changed app="Safari" title="([A-Z,a-z])*anime" action="yabai -m window --space  Fun && yabai -m space --focus Fun"
