#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=application_launched app="Safari" action="yabai -m window --toggle native-fullscreen"

# yabai -m config external_bar all:26:0

# global settings
yabai -m config mouse_follows_focus             on
yabai -m config focus_follows_mouse             autofocus
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   float
yabai -m config window_border                   off
yabai -m config window_border_width             10
yabai -m config active_window_border_color      0xB2EBDBB2
yabai -m config normal_window_border_color      0xB2282828
yabai -m config window_opacity                  on
yabai -m config active_window_opacity 			1.0
yabai -m config normal_window_opacity 			0.9
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                  0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      0

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Masters"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Media"

# Space config
# yabai -m config --space 4 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off

# Primary
yabai -m rule --add app="Preview"               space=1
yabai -m rule --add app="Zoom"                  space=1
yabai -m rule --add app="Finder"                space=1


# Masters
yabai -m rule --add app="GoodNotes"             space=2
yabai -m rule --add app="Microsoft OneNote"     space=2

# Tools
yabai -m rule --add app="Terminal"              space=3
yabai -m rule --add app="VimR"                  space=3
yabai -m rule --add app="Sublime Text"          space=3
yabai -m rule --add app="PyCharm"          		space=3

# Media
yabai -m rule --add app="IINA"                  space=4
yabai -m rule --add app="Spotify"               space=4
yabai -m rule --add app="WhatsApp"              space=4
yabai -m rule --add app="Safari"                space=4
yabai -m rule --add app="Telegram"              space=4
