#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
spacebar -m config space_icon_color     0xff77D674
spacebar -m config power_icon_color     0xffA6D75F
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip     "battery-half" "battery-full"
spacebar -m config space_icon           "| space-shuttle"
spacebar -m config clock_icon           "clock"
spacebar -m config dnd_icon             ""
spacebar -m config text_font            "Font Awesome 5 Free:Regular:12.0"
spacebar -m config icon_font            "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color     0xff202020
spacebar -m config foreground_color     0xffa8a8a8
spacebar -m config space_icon_strip     "home folder-open" "robot university" "terminal gamepad" "film headphones" "tools archive"
